### ISSUE TITLE
Fix uri-encoded query string parameters handling (legal and illegal)

### ISSUE THREAD

**Issue by idanga** [renatoathaydes/rawhttp#15]
There are three distinct but related issues here:
1) The following raw request will fail to parse correctly into an HTTP request (allowIllegalCharacters set to **off**):

```
GET /hello?encoded=%2F%2Fencoded%3Fa%3Db%26c%3Dd&json=%7B%22a%22%3A%20null%7D HTTP/1.1\r\n
Host: www.example.com\r\n\r\n
```

This is because the "withHost" method of RequestLine incorrectly handles the encoded '&' (%26),  
and it will break the query string into ` %2F%2Fencoded%3Fa%3Db -- & -- %3Dd&json=%7B%22a%22%3A%20null%7D`

(This will also affect parsing with allowIllegalCharacters **on**)

2) The following raw request will fail as well, :
```
GET /hello/{illegal}?url=%2F%2Fencoded%3Fa%3Db%26c%3Dd HTTP/1.1\r\n
Host: www.example.com\r\n\r\n
```
This time with a subtle double-encoding of the already encoded query string.
I guess this is a product decision - to not re-encode legal uri encoded part.

And additional wrinkle - even if there is not double-encoding, there is still the encoded '&' issue.

**Comment by renatoathaydes** [comment]
> The following raw request will fail to parse correctly into an HTTP request (allowIllegalCharacters set to off):

That's not true. The URL is parsed correctly as proven by [this test](https://github.com/renatoathaydes/rawhttp/commit/c42a5a9405d44cdbfa5c995ba57f3f8d652348a6).

This Kotlin code prints the expected values:

```kotlin
        val req = RawHttp().parseRequest(
                "GET /hello?encoded=%2F%2Fencoded%3Fa%3Db%26c%3Dd&json=%7B%22a%22%3A%20null%7D HTTP/1.1\r\n" +
                        "Host: www.example.com\r\n\r\n").eagerly()
        println("method: ${req.method}")
        println("host: ${req.uri.host}")
        println("path: ${req.uri.path}")
        println("query: ${req.uri.query}")
```

Result:

```
method: GET
host: www.example.com
path: /hello
query: encoded=//encoded?a=b&c=d&json={"a": null}
```

> (This will also affect parsing with allowIllegalCharacters on)

With that option on, the parsing does not fail either, but it does double-encode the String. That's expected behaviour because that option is meant to be used for writing URIs by hand, so it is expected that  the query is not already encoded.

>     The following raw request will fail as well, :
> GET /hello/{illegal}?url=%2F%2Fencoded%3Fa%3Db%26c%3Dd HTTP/1.1\r\n
> Host: www.example.com\r\n\r\n

This should fail with the default parser (as it contains illegal characters!), and it does... but it does not fail to parse with allowIllegalCharacters on:

```kotlin
        val req = RawHttp(RawHttpOptions.newBuilder().allowIllegalStartLineCharacters().build())
                .parseRequest("GET /hello/{illegal}?url=%2F%2Fencoded%3Fa%3Db%26c%3Dd HTTP/1.1\r\n" +
                        "Host: www.example.com\r\n\r\n").eagerly()
        println("method: ${req.method}")
        println("host: ${req.uri.host}")
        println("path: ${req.uri.path}")
        println("query: ${req.uri.query}")
```

Result:

```
method: GET
host: www.example.com
path: /hello/{illegal}
query: url=%2F%2Fencoded%3Fa%3Db%26c%3Dd
```

Again, as expected, the query was "double-encoded" so it shows as being still encoded above. To avoid that, use the option that does not allow illegal characters - and fix the path using some other means.

I think what you are looking for is an option that allows illegal characters, but still does not encode the query - that's impossible because when you ask for RawHTTP to allow illegal characters, it's implicitly assuming it needs to encode the characters in all parts of the URI!

My suggestion is that you pre-process your URIs before passing it on to RawHTTP to resolve variables or whatever it is you're trying to do.

**Comment by idanga** [comment]
@renatoathaydes the UT you mentioned proves there **is** a bug:
the original query string is `encoded=%2F%2Fencoded%3Fa%3Db%26c%3Dd&json=...`
After decoding, the variable `encoded` should have the value `"//encoded?a=b&c=d"`,
but instead, the parser will break it into two variables: `encoded=%2F%2Fencoded%3Fa%3Db` AND `c=d`, this is incorrect.

I take it as a product decision to implicitly assume to encode ALL illegal characters (even if some part is legally encoded), so I will not press further here.

**Comment by renatoathaydes** [comment]
>  After decoding, the variable encoded should have the value "//encoded?a=b&c=d",
but instead, the parser will break it into two variables: encoded=%2F%2Fencoded%3Fa%3Db AND c=d, this is incorrect.

You are correct! I had missed that... looks like `%26` is being interpreted as `&`.

> Edit: the error is in passing the uri.getQuery() into the c'tor of java.net.URI, in the "withHost" method of RequestLine.

Hm... the `URI` constructor documents that any illegal character in the query parameter will be percent-encoded, so the code is actually correct in passing in `uri.getQuery()` (the unencoded version of the query). If I change that, an existing test fails:

```kotlin
    RawHttp().parseRequest("GET /hello?field=encoded%20value HTTP/1.0\nHost: www.example.com").eagerly().run {
        method shouldBe "GET"
        startLine.httpVersion shouldBe HttpVersion.HTTP_1_0
        uri.path shouldBe "/hello"
        uri.query shouldBe "field=encoded value"
        toString() shouldBe "GET /hello?field=encoded%20value HTTP/1.0\r\nHost: www.example.com\r\n\r\n"
        headers.asMap() shouldEqual mapOf("HOST" to listOf("www.example.com"))
        body should notBePresent()
    }
```

This test should pass: `uri.query shouldBe "field=encoded value"` but it fails due to:

```
Expected :field=encoded value
Actual   :field=encoded%20value
```

I will think about this tonight and come up with a fix that works in both cases. Thanks for bringing it up.
