### ISSUE TITLE
Make the checking of host value as configurable

### ISSUE THREAD

**Issue by noviceamateur** [renatoathaydes/rawhttp#24]
I am trying to convert a string to a http request using this library which has no host.
String - > 

> GET /storage/ua/example.psd/:applicationMetadata
> content-type: application/json

The current code mandates the presence of host value which I dont have nor do I want. 
Could this be made optional using some configuration ?

**Comment by renatoathaydes** [comment]
The host is mandatory according to the RFC.
There's an option to automatically set the Host header when you parse a request if the header is missing, but in that case the host must appear in the start-line, e.g. `GET https://myhost.com/storage` otherwise there's no way at all to know where to send the request to.
