### ISSUE TITLE
parseResponse results in "Illegal character in HTTP header name" exception

### ISSUE THREAD

**Issue by paronix** [renatoathaydes/rawhttp#56]
I've issued the following CURL statement:

`curl -skLIXGET --http1.1 -m 30 -b curlcookies --url http://www.kijkwijzer.nl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"`

I feed the returning output (which I have attached to this issue) as a string to the parseResponse (String) method of the RawHttp library.  The parsing however ends up in an InvalidHttpResponse exception with the message "Illegal character in HTTP header name".

Is there something this library is not dealing with correctly or has kijkwijzer.nl simply misformed their response headers?

[response-headers.txt](https://github.com/renatoathaydes/rawhttp/files/9424250/response-headers.txt)

**Comment by renatoathaydes** [comment]
They server headers containing new-lines?

```
Content-Security-Policy:
          default-src 'self' www.google-analytics.com www.youtube.com;
          child-src 'self' www.youtube.com www.youtube-nocookie.com player.vimeo.com www.google.com;
```

HTTP message syntax looks like this:

```
HTTP-message   = start-line
                      *( header-field CRLF )
                      CRLF
                      [ message-body ]
```

What separates a header from another is a CRLF, or `\r\n`. Because RawHTTP allows users to write messages by hand, it also allows `\n` as a separator by default, but there's an option to disallow that when parsing messages.

Header values may otherwise contain anything, including binary data!

RawHTTP is probably treating new lines as the end of the header value, and as the next header looks like starts with whitespaces, which are not allowed, it breaks.

I had never seen new-lines being used like this. I will do some research and get back to you , but the browser seems happy to parse this so I suppose it's valid!?

**Comment by renatoathaydes** [comment]
The header seems to be valid if the examples in the MDN docs are correct:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#csp_in_workers

But this is contradicted in the MDN docs talking about headers in general:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#headers_2

> The whole header, including its value, presents as a single line.

I think the only way to understand whether this is valid or not is to interpret the ABNF carefullly:

```
   field-content = field-vchar [ 1*( SP / HTAB ) field-vchar ]
   field-name = token
   field-value = *( field-content / obs-fold )
   field-vchar = VCHAR / obs-text

    tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
    "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA
        ; any VCHAR, except delimiters
    token = 1*tchar
    obs-text       = %x80-FF
```

VCHAR is any visible ASCII character... the only forbidden characters are, therefore, the control characters, like NULL `0x00` and end-of-text `0x03`... so I suppose new-line is allowed as it's a visible character.

I will change the option to allow `/n` without preceding `\r` so that if you choose so, it will simply parse the new-lines as part of the string header value.

**Comment by paronix** [comment]
> I will change the option to allow /n without preceding \r so that if you choose so, it will simply parse the new-lines as part of the string header value.

It's not only a new-line character that is part of the value of the "Content-Security-Policy" header in the response of kijkwijzer.nl. There are also carriage returns in the value.

The one thing that strikes me is that everything that is part of the value of that header is on a new line but all those lines start with at least one space. Perhaps the value of a header can be spread over multiple lines, but only if they are preceded by white-space character(s)?

**Comment by renatoathaydes** [comment]
> Perhaps the value of a header can be spread over multiple lines, but only if they are preceded by white-space character(s)?

No such rule in the RFC as far as I can tell.

I am including the file you sent in my tests.

**Comment by renatoathaydes** [comment]
I parsed the file, replacing all `CR` and `LF` with visible strings between `[]`:

```
HTTP/1.1 200 OK[CR][LF]
Cache-Control: private[CR][LF]
Content-Type: text/html; charset=utf-8[CR][LF]
Set-Cookie: PerplexCookieApproval=0; expires=Sun, 25-Aug-2024 10:40:14 GMT; path=/; secure; HttpOnly; SameSite=Lax[CR][LF]
X-Content-Type-Options: nosniff[CR][LF]
X-Frame-Options: sameorigin[CR][LF]
X-XSS-Protection: 1; mode=block[CR][LF]
Strict-Transport-Security: max-age=31536000;[CR][LF]
Content-Security-Policy:[CR][LF]
          default-src 'self' www.google-analytics.com www.youtube.com;[CR][LF]
          child-src 'self' www.youtube.com www.youtube-nocookie.com player.vimeo.com www.google.com;[CR][LF]
    frame-src 'self' www.youtube.com forms.zohopublic.eu zfrmz.eu;[CR][LF]
          script-src 'self' 'unsafe-inline' 'unsafe-eval' www.perplex.nl s.ytimg.com *.google-analytics.com www.googletagmanager.com www.google.com www.gstatic.com www.youtube.com player.vimeo.com www.googletagmanager.com;[CR][LF]
          style-src 'self' 'unsafe-inline';[CR][LF]
          img-src 'self' data: rating.pegi.info *.google-analytics.com *.analytics.google.com www.perplex.nl i.ytimg.com www.gravatar.com img.youtube.com i.vimeocdn.com vumbnail.com;[CR][LF]
          font-src 'self' data:;[CR][LF]
    connect-src 'self' *.google-analytics.com *.analytics.google.com;[CR][LF]
          form-action 'self' forms.zohopublic.eu;[CR][LF]
          report-uri https://perplex.report-uri.com/r/default/csp/enforce;[CR][LF]
Date: Thu, 25 Aug 2022 10:40:14 GMT[CR][LF]
Content-Length: 95247
```

I think I found the section of the RFC that may allow this (though it's deprecated behaviour):

https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4

> Historically, HTTP header field values could be extended over
   multiple lines by preceding each extra line with at least one space
   or horizontal tab (obs-fold).  This specification deprecates such
   line folding except within the message/http media type
   ([Section 8.3.1](https://www.rfc-editor.org/rfc/rfc7230#section-8.3.1)).

Anyway, I think it's important to support older versions of the spec, so I will allow this kind of behaviour in the next release!

**Comment by paronix** [comment]
Any estimate on when the next release will be?

**Comment by renatoathaydes** [comment]
If the tests pass, I will publish this later tonight.

**Comment by renatoathaydes** [comment]
Git changed the new-lines in the test file :(. Bad luck, will try to fix that.

**Comment by renatoathaydes** [comment]
It's up on Maven central, version 2.5.1.

**Comment by paronix** [comment]
Thx for the quick response and fix. Will check out 2.5.1. tomorrow. 😃
