### ISSUE TITLE
Redirect cycle on 302 POST

### ISSUE THREAD

**Issue by kwrooijen** [renatoathaydes/rawhttp#64]
I'm running in to the issue that a POST returning a 302 redirects to the same URL resulting in a redirect cycle. I Believe the way POST -> 302 should be handled is to change the method to GET (but I could be wrong about this)

To fix this we might need to add

```java
        if (statusCode == 302) {
            method = "GET";
        }
```
Somewhere here

https://github.com/renatoathaydes/rawhttp/blob/d51e4cedc22c1478ea186538b70e22ef2fdb1e53/rawhttp-core/src/main/java/rawhttp/core/client/RedirectingRawHttpClient.java#L79-L83

I'm not sure if you need to remove the content body from the request in this case.

**Comment by kwrooijen** [comment]
This doesn't seem to work. The request gets redirected but I'm expecting to see a flash message saying "Invalid username or password". But instead I just see the page as if I directly accessed it with a GET.

**Comment by kwrooijen** [comment]
Ah, the problem is that I need to respect the `Set-Cookie` header. I'll take another look later.

**Comment by renatoathaydes** [comment]
The behaviour for 302's is described [here](https://www.rfc-editor.org/rfc/rfc7231#section-6.4.3).

I don't see a problem with the way it's currently implemented. Changing the method to GET is deprecated behaviour.

If you don't want the redirect to happen automatically, don't use the redirecting client and implement the behaviour you want using your own client wrapper class.

If you need to handle cookies, you need to use the [cookies module](https://renatoathaydes.github.io/rawhttp/rawhttp-modules/cookies.html) as RawHTTP does not support cookies in the core module (because it's not part of the core HTTP spec). 

If you still think there's a real problem with the way the redirect is currently implemented, please let me know.
